import type { ActionPriority, ActionOccurrence } from '../../../domain/planner/RecurrenceRule';
export interface LifeActionRecord {
  readonly estimateMinutes?: number | null;
  readonly scheduledStartMinute?: number | null;
  readonly scheduledDurationMinutes?: number | null;
  readonly priority?: ActionPriority | null;
  readonly occurrence?: ActionOccurrence | null;
  readonly completionGeneration?: number;
  readonly expectedContributions?: readonly { id: string; goalId: string }[] | null;
  readonly completedOn?: string | null;
  readonly schemaVersion: 1;
  readonly id: string;
  readonly title: string;
  readonly need?: string | null;
  readonly description: string | null;
  readonly expectedResult: string | null;
  readonly actualResult: string | null;
  readonly status: 'draft' | 'ready' | 'in_progress' | 'completed' | 'cancelled';
  readonly decisionId: string | null;
  readonly sphereId?: string | null;
  readonly directionId?: string | null;
  readonly goalId?: string | null;
  readonly parentActionId?: string | null;
  readonly isNext?: boolean;
  readonly plannedDate: string | null;
  readonly createdAt: string;
  readonly readyAt: string | null;
  readonly startedAt: string | null;
  readonly completedAt: string | null;
  readonly cancelledAt: string | null;
  readonly cancelReason: string | null;
  readonly archivedAt: string | null;
  readonly deletedAt?: string | null;
  readonly lastDeletedAt?: string | null;
  readonly restoredFromTrashAt?: string | null;
  readonly rescheduleCount: number;
  readonly version: number;
}
