import type { WalkReflectionStage } from '../../domain/walk/WalkReflectionTemplate';
const prompts: Readonly<Record<WalkReflectionStage, string>> = {
  facts: 'Какие факты вам известны?',
  assumptions: 'Что здесь пока только предположение?',
  options: 'Какие варианты вы видите?',
  choiceCost: 'Какова цена каждого выбора?',
  smallestTest: 'Какой небольшой шаг поможет проверить решение?',
  situation: 'Что именно происходит?',
  rootCause: 'Что может быть причиной?',
  constraints: 'Какие ограничения действительно важны?',
  changeOptions: 'Что вы можете изменить?',
  nextExperiment: 'Какой небольшой шаг стоит попробовать после прогулки?',
  currentPosition: 'Где вы находитесь сейчас?',
  desiredResult: 'Какой результат вы хотите получить?',
  mainObstacle: 'Что больше всего мешает?',
  nearestLever: 'На что вы можете повлиять уже сейчас?',
  nextStep: 'Какой следующий шаг будет посильным?',
  context: 'Что изменилось вокруг вас?',
  constraint: 'Какое ограничение определяет выбор?',
  priority: 'Что сейчас важнее остального?',
  sacrifice: 'От чего можно отказаться?',
  mainResult: 'Какой результат вы хотите сохранить в фокусе?',
  whyImportant: 'Почему этот вопрос важен для вас сейчас?',
  whatKnown: 'Что вы уже знаете, а что пока только предполагаете?',
  doubts: 'Что вызывает больше всего сомнений?',
  overlookedOptions: 'Какие варианты вы пока не рассматриваете?',
  whatCleared: 'Что прояснилось, а что требует дополнительной информации?',
  onMyMind: 'Что сейчас занимает ваши мысли?',
  whatMissing: 'Чего вам сейчас не хватает?',
  wantChange: 'Что вы хотели бы изменить?',
  memorable: 'Что сегодня запомнилось?',
  gaveEnergy: 'Что дало силы, а что утомило?',
  carryTomorrow: 'Что хочется перенести в завтра?',
  canWait: 'Что может подождать?',
  giveAttention: 'На что вы хотите потратить своё внимание?',
  myView: 'Как вы видите эту ситуацию?',
  otherView: 'Чего вы не знаете о позиции другого человека?',
  discussDirectly: 'Что стоит обсудить напрямую?',
  simplify: 'Что можно упростить?',
  tryDifferently: 'Что попробовать иначе?',
  smallestExperiment: 'Как выглядел бы самый маленький эксперимент?',
  desiredOutcome: 'Какой результат вы хотите получить вместо этого?',
  previousAttempts: 'Что вы уже пробовали и что получилось?',
};
export function getWalkPrompt(stage: WalkReflectionStage | null): string | null {
  return stage === null ? null : prompts[stage];
}
