import {
  ActionActualResult,
  ActionCancelReason,
  ActionExpectedResult,
  LifeAction,
  LifeActionTitle,
  type LifeActionStatus,
} from '../../../domain/life-action';
import type { LifeActionRecord } from '../records/LifeActionRecord';
import {
  assertRecordAndSchemaVersion,
  createNullableValueObject,
  createValueObject,
  readEntityId,
  readBoolean,
  readIsoDate,
  readNullableDayDate,
  readNullableEntityId,
  readNullableIsoDate,
  readOptionalNullableIsoDate,
  readNullableString,
  readOptionalNullableString,
  readOptionalNullableEntityId,
  readNumber,
  readString,
  toNullableIsoDate,
} from './RecordMapperSupport';

export class LifeActionRecordMapper {
  public static toRecord(entity: LifeAction): LifeActionRecord {
    return {
      ...(entity.walkPlan === null ? {} : { walkPlan: entity.walkPlan }),
      estimateMinutes: entity.estimateMinutes,
      scheduledStartMinute: entity.scheduledStartMinute,
      scheduledDurationMinutes: entity.scheduledDurationMinutes,
      expectedContributions: entity.expectedContributions,
      completedOn: entity.completedOn,
      priority: entity.priority,
      occurrence: entity.occurrence,
      completionGeneration: entity.completionGeneration,
      schemaVersion: 1,
      id: entity.id.toString(),
      title: entity.title.toString(),
      need: entity.need,
      description: entity.description,
      expectedResult: entity.expectedResult?.toString() ?? null,
      actualResult: entity.actualResult?.toString() ?? null,
      status: entity.status,
      decisionId: entity.decisionId?.toString() ?? null,
      sphereId: entity.sphereId?.toString() ?? null,
      directionId: entity.directionId?.toString() ?? null,
      goalId: entity.goalId?.toString() ?? null,
      parentActionId: entity.parentActionId?.toString() ?? null,
      isNext: entity.isNext,
      plannedDate: entity.plannedDate?.toString() ?? null,
      createdAt: entity.createdAt.toISOString(),
      readyAt: toNullableIsoDate(entity.readyAt),
      startedAt: toNullableIsoDate(entity.startedAt),
      completedAt: toNullableIsoDate(entity.completedAt),
      cancelledAt: toNullableIsoDate(entity.cancelledAt),
      cancelReason: entity.cancelReason?.toString() ?? null,
      archivedAt: toNullableIsoDate(entity.archivedAt),
      deletedAt: toNullableIsoDate(entity.deletedAt),
      lastDeletedAt: toNullableIsoDate(entity.lastDeletedAt),
      restoredFromTrashAt: toNullableIsoDate(entity.restoredFromTrashAt),
      rescheduleCount: entity.rescheduleCount,
      version: entity.version,
    };
  }

  public static fromRecord(record: LifeActionRecord): LifeAction {
    assertRecordAndSchemaVersion(record);
    return LifeAction.rehydrate({
      walkPlan: record.walkPlan ?? null,
      estimateMinutes: record.estimateMinutes ?? null,
      scheduledStartMinute: record.scheduledStartMinute ?? null,
      scheduledDurationMinutes: record.scheduledDurationMinutes ?? null,
      expectedContributions: record.expectedContributions ?? null,
      ...(record.completedOn === undefined ? {} : { completedOn: record.completedOn }),
      priority: record.priority ?? null,
      occurrence: record.occurrence ?? null,
      completionGeneration: record.completionGeneration ?? 0,
      id: readEntityId(record, 'id'),
      title: createValueObject(record, 'title', LifeActionTitle.create),
      need: readOptionalNullableString(record, 'need'),
      description: readNullableString(record, 'description'),
      expectedResult: createNullableValueObject(
        record,
        'expectedResult',
        ActionExpectedResult.create,
      ),
      actualResult: createNullableValueObject(record, 'actualResult', ActionActualResult.create),
      status: readString(record, 'status') as LifeActionStatus,
      decisionId: readNullableEntityId(record, 'decisionId'),
      sphereId: readOptionalNullableEntityId(record, 'sphereId'),
      goalId: readOptionalNullableEntityId(record, 'goalId'),
      directionId: readOptionalNullableEntityId(record, 'directionId'),
      parentActionId: readOptionalNullableEntityId(record, 'parentActionId'),
      isNext: record.isNext === undefined ? false : readBoolean(record, 'isNext'),
      plannedDate: readNullableDayDate(record, 'plannedDate'),
      createdAt: readIsoDate(record, 'createdAt'),
      readyAt: readNullableIsoDate(record, 'readyAt'),
      startedAt: readNullableIsoDate(record, 'startedAt'),
      completedAt: readNullableIsoDate(record, 'completedAt'),
      cancelledAt: readNullableIsoDate(record, 'cancelledAt'),
      cancelReason: createNullableValueObject(record, 'cancelReason', ActionCancelReason.create),
      archivedAt: readNullableIsoDate(record, 'archivedAt'),
      deletedAt: readOptionalNullableIsoDate(record, 'deletedAt'),
      lastDeletedAt: readOptionalNullableIsoDate(record, 'lastDeletedAt'),
      restoredFromTrashAt: readOptionalNullableIsoDate(record, 'restoredFromTrashAt'),
      rescheduleCount: readNumber(record, 'rescheduleCount'),
      version: readNumber(record, 'version'),
    });
  }
}
